import type { ReactNode } from 'react'
import type { ReportCard } from '../lib/types'
import { useAuth } from '../lib/auth'
import { formatDate, formatPercent } from '../lib/format'
import { Alert, Button, StatusBadge } from './index'

/**
 * Snapshot shape as produced by `buildSectionReportCards` (backend service).
 * Kept loose/optional so cards generated by earlier backends still render.
 */
interface SnapshotSubject {
  name?: string
  subject_name?: string
  code?: string
  subject_code?: string
  percentage?: number | null
  letter?: string | null
  gpa?: number | null
  credit_hours?: number | string | null
}

interface Snapshot {
  generated_at?: string
  term_id?: string
  grading_scale?: { id?: string | null; name?: string | null }
  subjects?: SnapshotSubject[]
  overall_percentage?: number | null
  overall_gpa?: number | null
  letter?: string | null
  class_rank?: number | null
  class_size?: number | null
  attendance?: {
    present?: number
    absent?: number
    late?: number
    excused?: number
    sick?: number
    percentage?: number
  }
  exam_ineligible?: boolean
  // Legacy flat fields, retained for robustness.
  student_name?: string
  admission_no?: string
  section_name?: string
  term_name?: string
  attendance_pct?: number | null
  gpa?: number | null
  homeroom_comment?: string | null
  grading_scale_name?: string | null
}

export function ReportCardView({
  reportCard,
  actions,
  studentName,
  sectionName,
}: {
  reportCard: ReportCard
  actions?: ReactNode
  studentName?: string
  sectionName?: string
}) {
  const { school, timezone, locale } = useAuth()
  const snap = (reportCard.snapshot_json ?? {}) as Snapshot
  const subjects = snap.subjects ?? []
  const resolvedStudent =
    studentName ??
    snap.student_name ??
    `${reportCard.student?.first_name ?? ''} ${reportCard.student?.last_name ?? ''}`.trim()
  const resolvedSection = sectionName ?? snap.section_name ?? undefined
  const termName = snap.term_name ?? reportCard.term?.name ?? reportCard.term_name ?? undefined
  const overall = snap.overall_percentage ?? reportCard.overall_percentage ?? null
  const gpa = snap.overall_gpa ?? snap.gpa ?? reportCard.gpa ?? null
  const rank = snap.class_rank ?? reportCard.class_rank ?? null
  const classSize = snap.class_size ?? reportCard.class_size ?? null
  const attendance = snap.attendance?.percentage ?? snap.attendance_pct ?? reportCard.attendance_pct ?? null
  const scaleName = snap.grading_scale?.name ?? snap.grading_scale_name ?? null
  const comment = snap.homeroom_comment ?? reportCard.homeroom_comment ?? null

  return (
    <div className="report-card-print">
      <div className="print-toolbar no-print">
        {actions}
        <Button variant="secondary" onClick={() => window.print()}>
          Print
        </Button>
      </div>
      <div className="card">
        <div className="card-body">
          <div className="row-between" style={{ marginBottom: 'var(--sch-space-6)' }}>
            <div>
              <h1 style={{ fontSize: 'var(--sch-font-size-2xl)' }}>{school?.name ?? 'Scholarion Academy'}</h1>
              <div className="muted">Term report card{scaleName ? ` · ${scaleName}` : ''}</div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <StatusBadge status={reportCard.status} />
              {reportCard.version > 1 ? (
                <div className="muted mt-1">Revision v{reportCard.version}</div>
              ) : null}
            </div>
          </div>

          <div className="grid grid-4" style={{ marginBottom: 'var(--sch-space-6)' }}>
            <div>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Student</div>
              <div style={{ fontWeight: '600' }}>{resolvedStudent || '\u2014'}</div>
            </div>
            <div>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Admission no.</div>
              <div>{snap.admission_no ?? reportCard.student?.admission_no ?? '\u2014'}</div>
            </div>
            <div>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Section</div>
              <div>{resolvedSection ?? '\u2014'}</div>
            </div>
            <div>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Term</div>
              <div>{termName ?? '\u2014'}</div>
            </div>
          </div>

          <div className="table-scroll" style={{ marginBottom: 'var(--sch-space-6)' }}>
            <table className="table">
              <thead>
                <tr>
                  <th>Subject</th>
                  <th className="num">Percentage</th>
                  <th className="num">Letter</th>
                  <th className="num">GPA</th>
                </tr>
              </thead>
              <tbody>
                {subjects.map((s, i) => {
                  const name = s.subject_name ?? s.name
                  const code = s.subject_code ?? s.code
                  return (
                    <tr key={i}>
                      <td>
                        {name}
                        {code ? <span className="muted"> ({code})</span> : null}
                      </td>
                      <td className="num">{formatPercent(s.percentage ?? null)}</td>
                      <td className="num">{s.letter ?? '\u2014'}</td>
                      <td className="num">{s.gpa ?? '\u2014'}</td>
                    </tr>
                  )
                })}
                {subjects.length === 0 ? (
                  <tr>
                    <td colSpan={4} className="muted">
                      No subject grades recorded.
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>

          <div className="grid grid-4" style={{ marginBottom: 'var(--sch-space-6)' }}>
            <div className="card-body" style={{ background: 'var(--sch-bg-inset)', borderRadius: 'var(--sch-radius-md)' }}>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Overall %</div>
              <div style={{ fontWeight: '600', fontSize: 'var(--sch-font-size-xl)' }}>{formatPercent(overall)}</div>
            </div>
            <div className="card-body" style={{ background: 'var(--sch-bg-inset)', borderRadius: 'var(--sch-radius-md)' }}>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>GPA</div>
              <div style={{ fontWeight: '600', fontSize: 'var(--sch-font-size-xl)' }}>{gpa ?? '\u2014'}</div>
            </div>
            <div className="card-body" style={{ background: 'var(--sch-bg-inset)', borderRadius: 'var(--sch-radius-md)' }}>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Class rank</div>
              <div style={{ fontWeight: '600', fontSize: 'var(--sch-font-size-xl)' }}>
                {rank ? `${rank} / ${classSize ?? '\u2014'}` : '\u2014'}
              </div>
            </div>
            <div className="card-body" style={{ background: 'var(--sch-bg-inset)', borderRadius: 'var(--sch-radius-md)' }}>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Attendance</div>
              <div style={{ fontWeight: '600', fontSize: 'var(--sch-font-size-xl)' }}>{formatPercent(attendance)}</div>
            </div>
          </div>

          {snap.exam_ineligible ? (
            <div style={{ marginBottom: 'var(--sch-space-6)' }}>
              <Alert tone="warning">Attendance below the minimum threshold — flagged exam-ineligible.</Alert>
            </div>
          ) : null}

          {comment ? (
            <div style={{ marginBottom: 'var(--sch-space-6)' }}>
              <div className="muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>Homeroom teacher comment</div>
              <p>{comment}</p>
            </div>
          ) : null}

          <div className="row-between muted" style={{ fontSize: 'var(--sch-font-size-xs)' }}>
            <span>
              {reportCard.published_at ? `Published ${formatDate(reportCard.published_at, { timezone, locale })}` : 'Draft'}
            </span>
            <span>snapshot {reportCard.snapshot_hash.slice(0, 12)}</span>
          </div>
        </div>
      </div>
    </div>
  )
}
